const String MALE = "MALE";
const String FEMALE = "FEMALE";
const String HEIGHT = "HEIGHT";
const String WEIGHT = "WEIGHT";
const String AGE = "AGE";
const String CALCULATE = "CALCULATE YOUR BMI";
const String OVERWEIGHT = "Over-weight";
const String NORMAL = "Normal";
const String UNDERWEIGHT = "Under-weight";
